spring:
  application:
    name: custom-chatbot
  
  datasource:
    url: jdbc:h2:mem:demodb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: false
    open-in-view: false
  
  h2:
    console:
      enabled: true
  
  security:
    jwt:
      secret: demo-secret-key-for-demonstration-purposes-only-make-it-long-enough-for-hs512-algorithm-security-requirements
      expiration: 86400000 # 24시간

# AI 서비스 설정
ai:
  mock:
    enabled: true
  
  openai:
    enabled: false
    api-key: demo-openai-key
    base-url: https://api.openai.com/v1
  
  claude:
    enabled: false
    api-key: demo-claude-key
    base-url: https://api.anthropic.com
  
  gemini:
    enabled: true
    api-key: demo-gemini-key
    base-url: https://generativelanguage.googleapis.com

# 로깅 설정
logging:
  level:
    com.kafibara.chatbot: DEBUG
    org.springframework.boot.autoconfigure: DEBUG
    org.springframework.security: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 서버 설정
server:
  port: 8080

# Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: always

# 애플리케이션 정보
info:
  app:
    name: Custom Chatbot Service
    description: AI 챗봇 서비스 - 데모 환경
    version: 1.0.0
    profile: demo
